import os
import re
import glob
import shlex

# Configuration
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(ROOT_DIR, "html")

if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

def get_html_filename(md_filename):
    return md_filename.replace('.md', '.html')

def parse_markdown(text, current_filename):
    html = text
    # Headers
    html = re.sub(r'^# (.*$)', r'<h1>\1</h1>', html, flags=re.MULTILINE)
    html = re.sub(r'^## (.*$)', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'^### (.*$)', r'<h3>\1</h3>', html, flags=re.MULTILINE)
    html = re.sub(r'^#### (.*$)', r'<h4>\1</h4>', html, flags=re.MULTILINE)
    
    # Bold
    html = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', html)
    
    # Lists
    # Simple list parsing
    html = re.sub(r'^\* (.*$)', r'<ul><li>\1</li></ul>', html, flags=re.MULTILINE)
    html = html.replace('</ul>\n<ul>', '')
    
    # Blockquotes
    html = re.sub(r'^> (.*$)', r'<blockquote>\1</blockquote>', html, flags=re.MULTILINE)
    html = html.replace('</blockquote>\n<blockquote>', '<br>')

    # Links
    def replace_link(match):
        link_text = match.group(1)
        link_url = match.group(2)
        
        # Check if it's a markdown file link
        if link_url.endswith('.md'):
            # If it's a local file, convert to HTML link
            target_filename = os.path.basename(link_url)
            return f'<a href="{get_html_filename(target_filename)}">{link_text}</a>'
        
        # Default behavior for external links
        return f'<a href="{link_url}" target="_blank">{link_text}</a>'

    html = re.sub(r'\[(.*?)\]\((.*?)\)', replace_link, html)
    
    # Code blocks
    # Simple code block handler
    html = re.sub(r'```(.*?)```', r'<pre><code>\1</code></pre>', html, flags=re.DOTALL)
    
    # Paragraphs (simple)
    html = re.sub(r'\n\n', '<br><br>', html)
    
    return html

def get_sidebar_html(md_files, current_file):
    links = []
    links.append(f'<li><a href="index.html" class="{"active" if current_file == "index.html" else ""}">Home</a></li>')
    
    for filepath in md_files:
        filename = os.path.basename(filepath)
        html_filename = get_html_filename(filename)
        display_name = filename.replace('.md', '').replace('_', ' ')
        
        is_active = "active" if filename == current_file else ""
        links.append(f'<li><a href="{html_filename}" class="{is_active}">{display_name}</a></li>')
        
    return f"""
    <div id="sidebar">
        <h2>Documentation</h2>
        <ul>{''.join(links)}</ul>
        <div style="margin-top: 50px; font-size: 0.8em; color: #95a5a6;">
            <p>Generated by AI Assistant</p>
        </div>
    </div>
    """

def get_page_template(title, content, sidebar):
    return f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; display: flex; height: 100vh; background-color: #f4f4f9; }}
        
        /* Sidebar Styles */
        #sidebar {{ width: 280px; background-color: #2c3e50; color: white; padding: 20px; overflow-y: auto; flex-shrink: 0; box-shadow: 2px 0 5px rgba(0,0,0,0.1); }}
        #sidebar h2 {{ color: #ecf0f1; font-size: 1.4em; border-bottom: 1px solid #34495e; padding-bottom: 15px; margin-top: 0; }}
        #sidebar ul {{ list-style: none; padding: 0; }}
        #sidebar li {{ margin: 8px 0; }}
        #sidebar a {{ color: #bdc3c7; text-decoration: none; transition: 0.2s; display: block; padding: 10px; border-radius: 6px; font-size: 0.95em; }}
        #sidebar a:hover {{ color: white; background-color: #34495e; transform: translateX(5px); }}
        #sidebar a.active {{ color: white; background-color: #3498db; font-weight: bold; }}
        
        /* Content Styles */
        #content-wrapper {{ flex-grow: 1; overflow-y: auto; position: relative; }}
        #content {{ max-width: 960px; margin: 40px auto; padding: 40px; background-color: white; box-shadow: 0 0 20px rgba(0,0,0,0.05); border-radius: 8px; min-height: 80vh; }}
        
        /* Typography */
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 15px; font-size: 2.2em; margin-top: 0; }}
        h2 {{ color: #34495e; margin-top: 40px; border-bottom: 1px solid #eee; padding-bottom: 8px; }}
        h3 {{ color: #2980b9; margin-top: 30px; }}
        h4 {{ color: #7f8c8d; margin-top: 20px; }}
        p {{ line-height: 1.6; color: #333; }}
        
        /* Elements */
        pre {{ background-color: #282c34; color: #abb2bf; padding: 20px; border-radius: 8px; overflow-x: auto; font-size: 0.9em; box-shadow: inset 0 0 10px rgba(0,0,0,0.2); }}
        code {{ font-family: 'Consolas', 'Monaco', monospace; }}
        a {{ color: #3498db; text-decoration: none; font-weight: 500; }}
        a:hover {{ text-decoration: underline; }}
        blockquote {{ border-left: 4px solid #3498db; margin: 20px 0; padding: 15px 20px; color: #555; background-color: #f8fbff; border-radius: 0 4px 4px 0; }}
        ul, ol {{ padding-left: 25px; line-height: 1.6; }}
        li {{ margin-bottom: 5px; }}
        
        /* Scrollbar */
        ::-webkit-scrollbar {{ width: 8px; height: 8px; }}
        ::-webkit-scrollbar-track {{ background: #f1f1f1; }}
        ::-webkit-scrollbar-thumb {{ background: #bdc3c7; border-radius: 4px; }}
        ::-webkit-scrollbar-thumb:hover {{ background: #95a5a6; }}
    </style>
</head>
<body>
    {sidebar}
    <div id="content-wrapper">
        <div id="content">
            {content}
        </div>
    </div>
</body>
</html>
    """

def generate_dashboard():
    md_files = glob.glob(os.path.join(ROOT_DIR, "**/*.md"), recursive=True)
    # Sort files
    md_files.sort(key=lambda x: (0 if "Index.md" in x else 1, os.path.basename(x)))
    
    print(f"Found {len(md_files)} md files.")

    # Generate individual pages
    for filepath in md_files:
        filename = os.path.basename(filepath)
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
        except Exception as e:
            print(f"Error reading {filename}: {e}")
            continue
            
        html_content = parse_markdown(content, filename)
        sidebar = get_sidebar_html(md_files, filename)
        
        full_html = get_page_template(
            title=filename.replace('.md', ''),
            content=html_content,
            sidebar=sidebar
        )
        
        output_filename = get_html_filename(filename)
        output_path = os.path.join(OUTPUT_DIR, output_filename)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(full_html)
            
        print(f"Generated: {output_filename}")

    # Generate Index Page (Landing Page)
    index_sidebar = get_sidebar_html(md_files, "index.html")
    index_content = """
    <h1>FishingGame Project Dashboard</h1>
    <p>Welcome to the project documentation center.</p>
    <p>Please select a document from the sidebar to begin.</p>
    <h2>Quick Links</h2>
    <ul>
    """
    for filepath in md_files:
        fname = os.path.basename(filepath)
        hname = get_html_filename(fname)
        dname = fname.replace('.md', '').replace('_', ' ')
        index_content += f'<li><a href="{hname}">{dname}</a></li>'
    index_content += "</ul>"
    
    index_html = get_page_template("Dashboard Home", index_content, index_sidebar)
    with open(os.path.join(OUTPUT_DIR, "index.html"), 'w', encoding='utf-8') as f:
        f.write(index_html)
        
    print(f"Generated: index.html")
    print(f"All files are in: {OUTPUT_DIR}")

if __name__ == "__main__":
    generate_dashboard()

