param(
    [string]$InputPath,
    [string]$OutputName = ""
)
# 1. Validate Input
if (-not $InputPath) {
    Write-Error "Please provide an InputPath. Usage: .\ConvertMdToHtml.ps1 -InputPath '..\KnowledgeBase\MyDoc.md'"
    return
}
$FullPath = Resolve-Path $InputPath
if (-not (Test-Path $FullPath)) {
    Write-Error "Input file not found: $FullPath"
    return
}
$FileName = [System.IO.Path]::GetFileNameWithoutExtension($FullPath)
if ($OutputName -eq "") {
    $OutputName = $FileName
}
# 2. Prepare Output Path
$HtmlDir = "G:\Copilot_OutPut\FishingGame\html"
if (-not (Test-Path $HtmlDir)) { New-Item -ItemType Directory -Path $HtmlDir -Force | Out-Null }
$OutputPath = Join-Path $HtmlDir "$OutputName.html"
# 3. Read Markdown Content
$mdContent = Get-Content -Path $FullPath -Raw -Encoding UTF8
# 4. Simple Markdown Parsing logic (Regex based)
# Escaping HTML chars
$htmlBody = $mdContent -replace "&", "&amp;" -replace "<", "&lt;" -replace ">", "&gt;"
# Code Blocks ```...```
$htmlBody = [regex]::Replace($htmlBody, "(?s)```(.*?)```", { param($m) 
    return "<pre>" + $m.Groups[1].Value + "</pre>" 
})
# Headers
$htmlBody = $htmlBody -replace '(?m)^# (.*?)$', '<h1>$1</h1>'
$htmlBody = $htmlBody -replace '(?m)^## (.*?)$', '<h2>$1</h2>'
$htmlBody = $htmlBody -replace '(?m)^### (.*?)$', '<h3>$1</h3>'
$htmlBody = $htmlBody -replace '(?m)^#### (.*?)$', '<h4>$1</h4>'
# Bold
$htmlBody = $htmlBody -replace '\*\*(.*?)\*\*', '<strong>$1</strong>'
# Inline Code
$htmlBody = $htmlBody -replace '`([^`]+)`', '<code>$1</code>'
# Links [text](url)
$htmlBody = $htmlBody -replace '\[(.*?)\]\((.*?)\)', '<a href="$2">$1</a>'
# Lists - (Simple)
$htmlBody = $htmlBody -replace '(?m)^- (.*?)$', '<li>$1</li>'
# Wrap lists (Heuristic: consecutive lis should be in ul)
# For simplicity in this script, we rely on CSS to style list items, or just basic replacement.
# A perfect parser is complex, but this handles basic bullet points.
# Paragraphs (Blank lines indicate new paragraph)
$htmlBody = $htmlBody -replace '(?m)^\s*$', '<br/>' 
# 5. Wrap in HTML Template with CSS
$htmlTemplate = @"
<!DOCTYPE html>
<html lang='zh-CN'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>$FileName</title>
    <style>
        body { font-family: "Microsoft YaHei", sans-serif; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 20px; color: #333; background-color: #fcfcfc; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 30px;}
        h2 { color: #2980b9; margin-top: 25px; border-left: 4px solid #3498db; padding-left: 10px; background: #ecf0f1; padding-top:5px; padding-bottom:5px;}
        h3 { color: #16a085; margin-top: 20px; }
        code { background-color: #f8f9fa; padding: 2px 5px; border-radius: 4px; font-family: Consolas, monospace; color: #e74c3c; border: 1px solid #e1e4e8; }
        pre { background-color: #282c34; color: #abb2bf; padding: 15px; border-radius: 5px; overflow-x: auto; font-family: Consolas, monospace; line-height: 1.4; }
        strong { color: #c0392b; }
        li { margin-bottom: 5px; }
        a { color: #3498db; text-decoration: none; font-weight: bold; }
        a:hover { text-decoration: underline; }
        blockquote { border-left: 4px solid #ddd; padding-left: 15px; color: #777; margin: 15px 0; }
        .timestamp { font-size: 0.8em; color: #999; text-align: right; border-top: 1px solid #eee; margin-top: 50px; padding-top: 10px; }
    </style>
</head>
<body>
    $htmlBody
    <div class="timestamp">Generated by AI Assistant Toolchain on $(Get-Date)</div>
</body>
</html>
"@
# 6. Write Output
$htmlTemplate | Out-File -FilePath $OutputPath -Encoding UTF8
Write-Host "Success: Converted '$FileName' to HTML."
Write-Host "Location: $OutputPath"
